version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: strava-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      RUST_LOG: info
      # add STRAVA_CLIENT_ID, STRAVA_SECRET, DATABASE_URL etc. here

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: strava-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    volumes:
      - ./frontend:/app
    command: npm run dev
    depends_on:
      - backend
