version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: strava-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      RUST_LOG: info
      # add STRAVA_CLIENT_ID, STRAVA_SECRET, DATABASE_URL etc. here

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: strava-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    volumes:
      - ./frontend:/app
    command: npm run dev
    depends_on:
      - backend

  database:
    image: postgres:16
    container_name: strava_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: strava_user
      POSTGRES_PASSWORD: strava_password
      POSTGRES_DB: strava_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
